# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
jobs:
  - job: TEST
    pool:
      vmImage: macos-latest
    steps:
      - bash: curl -so- 86.re/bench.sh | bash