# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none # No CI build
schedules:
- cron: "0 1,5,8 * * 1-5"
  displayName: Test the availability of the API at the working day
  branches:
    include:
    - master