# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
pool:
  vmImage: ubuntu-latest
schedules:
- cron: "0 1,5,8 * * 1-5"
  displayName: Test the availability of the API at the working day
  branches:
    include:
    - master
  always: true

steps:
- checkout: self
  persistCredentials: true
  clean: true
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'
- script: |
    pip install requests
  displayName: 'Prepare Environment'
- script: |
        echo "$(ID_LIST)" > idlist.txt
        echo "$(KEY_LIST)" > keylist.txt
        sed -i '10 r idlist.txt' testapi.py
        sed -i '11 r keylist.txt' testapi.py
        echo $ID_LIST2 > idlist2.txt
        echo $KEY_LIST2 > keylist2.txt
        sed -i '12 r idlist2.txt' testapi.py
        sed -i '13 r keylist2.txt' testapi.py
  displayName: 'Reading Secrets'
- script: |
        python testapi.py