# Starter pipeline 
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
pool:
  vmImage: ubuntu-latest
schedules:
- cron: "45 2 15 * *"
  displayName: Test the availability of the API at the working day
  branches:
    include:
    - master
  always: true
steps:
- checkout: self
  persistCredentials: true
  clean: true

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'
  displayName: 'Prepare Environment'
- script: |
        python updaterand.py
        git config --global user.email $(GitMail)
        git config --global user.name $(GitName)
        git add .
        git commit -m "update new randapi" -a
- script: |
        # mkdir ~/.ssh
        # touch ~/.ssh/id_rsa
        # chmod 0600 id_rsa
        # touch ~/.ssh/known_hosts
        # echo "$(SSH_KEY)" >> ~/.ssh/id_rsa
        # ssh-keyscan -t rsa ssh.dev.azure.com >> ~/.ssh/known_hosts
        # git push git@ssh.dev.azure.com:v3/XiaoShiTEST/Test-the-availability-of-the-API-at-the-working-day/Test-the-availability-of-the-API-at-the-working-day HEAD:master --force
        # git push https://$(USERNAME):$(TOKEN)@dev.azure.com/XiaoShiTEST/Test-the-availability-of-the-API-at-the-working-day/_git/Test-the-availability-of-the-API-at-the-working-day HEAD:master --force 
        git push origin HEAD:master --force 
# - task: BatchScript@1
#   inputs:
#     filename: merge.bat
  displayName: 'Push'