# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
pool:
  vmImage: ubuntu-latest
schedules:
- cron: "45 2 15 * *"
  displayName: Test the availability of the API at the working day
  branches:
    include:
    - master
  always: true
steps:
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'
  displayName: 'Prepare Environment'
- script: |
        python updaterand.py
