# Starter pipeline 
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
pool:
  vmImage: ubuntu-latest
schedules:
- cron: "45 2 15 * *"
  displayName: Test the availability of the API at the working day
  branches:
    include:
    - master
  always: true
steps:
- checkout: self
  persistCredentials: true
  clean: true

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'
  displayName: 'Prepare Environment'
- script: |
        python updaterand.py
        # git config --global user.email $(GitMail)
        # git config --global user.name $(GitName)
        git add .
        git commit -m "update new randapi" -a
- script: |
        git push origin
        # git push https://XiaoShiTEST@dev.azure.com/XiaoShiTEST/Test-the-availability-of-the-API-at-the-working-day/_git/Test-the-availability-of-the-API-at-the-working-day HEAD:refs/heads/master --force 
# - task: BatchScript@1
#   inputs:
#     filename: merge.bat
  displayName: 'Push'