# Starter pipeline 
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
pool:
  vmImage: ubuntu-latest
schedules:
- cron: "23 1-4,6-13 * * 1-5"
  displayName: update-token
  branches:
    include:
    - master
  always: true
steps:
- checkout: self
  persistCredentials: true
  clean: true

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'
- script: |
        pip install requests
        python updaterand.py
        git config --global user.email $(GitMail)
        git config --global user.name $(GitName)
  displayName: 'Prepare Environment'

- script: |
        cp updatetoken.py updatetoken2.py
        echo "$(ID_LIST)" > idlist.txt
        echo "$(KEY_LIST)" > keylist.txt
        sed -i '10 r idlist.txt' updatetoken2.py
        sed -i '11 r keylist.txt' updatetoken2.py
        echo "$(ID_LIST2)" > idlist2.txt
        echo "$(KEY_LIST2)" > keylist2.txt
        sed -i '12 r idlist2.txt' updatetoken2.py
        sed -i '13 r keylist2.txt' updatetoken2.py
  displayName: 'Read Secrets'

- script: |
        python updatetoken2.py
  displayName: 'Update token'

- script: |
        rm -f updatetoken2.py
        rm -f idlist.txt
        rm -f keylist.txt
        rm -f idlist2.txt
        rm -f keylist2.txt
  displayName: 'Delete Secrets'

- script: |
        git add .
        git commit -m "update new refresh_token" -a
        git push origin HEAD:master
  displayName: 'Push'